spring:
    application:
        name: dispositif



    datasource:
        url: "jdbc:mysql://localhost:3306/dispositif"
        username: "root"
        password: ""
    jpa:
        open-in-view: false
        database: MYSQL
        hibernate:
            ddl-auto: update

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 15MB


server: 
    port: 8082

    
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#       fetch-registry: false
#       register-with-eureka: false



# springdoc:
#   swagger-ui:
#     path: /swagger-ui-custom.html